# Generated by Django 5.1 on 2024-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Avatar',
            field=models.ImageField(blank=True, default='hoodie.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
