# Generated by Django 5.1 on 2024-09-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_blogs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='profilepic',
        ),
    ]
