# Generated by Django 5.1 on 2024-09-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_blogs_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='mainapp.profiles'),
        ),
    ]
