# Generated by Django 5.1 on 2024-09-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_profiles_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
