# Generated by Django 5.1 on 2024-09-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_blogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='mainapp.profiles'),
        ),
    ]
