# Generated by Django 5.1.1 on 2024-10-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_blogs_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='profile',
        ),
    ]
